before_install:
  - gem install bundler
bundler_args: --without development
language: ruby
rvm:
  - 2.4.1
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
script: bundle exec thor spec
sudo: false
cache: bundler
